### ISSUE TITLE
Designation is coded on Admin page.

### ISSUE THREAD

**Issue by dkasb** [pkgodara/eOrg#50]
Hi, I'm facing a problem knowing the designations of users as it displays coded like ( L_1 , L_1_2 , etc.).
It would be great if it displays proper designations in readable format.

**Comment by NabeelQaiser** [comment]
Hi,
Glad to know that you have devoted your time in fishing the mentioned issue (#50).

However, I would like to know that if I provide the dedicated button to view the 'users' category wise (by selecting category of your choice), would it satisfy your requirements.

(P.S. : The feature of mentioning the proper designation would also be there)

**Comment by dkasb** [comment]
@NabeelQaiser that would be fine. would there be any option to view all users?
